// ── CURRICULUM DATA ──────────────────────────────────────────────────────
// Structure: sections → subjects → groups (optional) → topics

const EXAM_DATE = '2027-05-30';

const SECTIONS = [
  {
    id: 'gs1', label: 'GS — 1',
    subjects: [
      {
        id: 'history', label: 'History',
        groups: [
          { id: 'ancient', label: 'Ancient History', topics: [
            'Introduction',
            'Construction of Ancient Indian History',
            'Pre-Historic India',
            'Harappan Culture / Indus Valley Civilization (IVC)',
            'Vedic Culture (1500–600 BCE)',
            'Philosophical Thoughts',
            'Magadha and Invasions',
            'Mauryan Empire (321–185 BCE)',
            'Post-Mauryan (200 BC to 200 CE)',
            'Sangam Age (300 BC–300 CE)',
            'Gupta Empire (275–600 AD)',
            'Harshavardhana (606–647 AD)',
            'South Indian Kingdoms',
            'Temple Architecture',
          ]},
          { id: 'medieval', label: 'Medieval History', topics: [
            'Early Medieval India',
            'Delhi Sultanate (1206–1526 AD)',
            'Other Kingdoms',
            'Religious / Spiritual Movements',
            'Mughal Empire (1526–1857 AD)',
            'Marathas (1674–1818 AD)',
            'Architecture in Modern India',
          ]},
          { id: 'modern', label: 'Modern History', topics: [
            'Later Mughals',
            'The Coming of Europeans',
            'British Conquest in India',
            'India under the British Rule — Administrative and Judicial Departments',
            'India under the British Rule — British Policies in India',
            'India under the British Rule — Impact of British Rule in India',
            'India under the British Rule — Development of Indian Press',
            'India under the British Rule — Development of Education',
            'Rising Resentments against the Rule',
            'Reform Movements',
            'The Struggle Begins',
            'National Movement (1905–1918)',
            'Era of Mass Nationalism (1919–1939)',
            'Towards Freedom and Partition (1939–1947)',
          ]},
          { id: 'artculture', label: 'Art and Culture', topics: [
            'Paintings',
            'Handicrafts',
            'Music',
            'Classical Dance Forms',
            'Folk Dance Forms',
            'Indian Theatres',
            'Puppetry',
            'Martial Arts',
            'Miscellaneous',
          ]},
          { id: 'postindependence', label: 'Post-Independent India', topics: [
            'Post-Independent India',
          ]},
          { id: 'worldhistory', label: 'World History', topics: [
            '18th to 20th Century Milestones',
            'Industrial Revolution',
            'World Wars',
            'Redrawal of National Boundaries',
            'Colonization',
            'Decolonization',
          ]},
        ],
      },
      {
        id: 'geography', label: 'Geography',
        groups: [
          { id: 'geomorphology', label: 'Geomorphology', topics: [
            'Origins of Continents and Oceans',
            'Interior of the Earth – Volcanism - Earthquakes',
            'Geomorphic Process',
            'Landforms and their Evolution',
            'Rocks',
          ]},
          { id: 'climatology', label: 'Climatology', topics: [
            'Atmosphere – Composition and Structure',
            'Solar Radiation',
            'Temperature',
            'Atmospheric Pressure and Wind',
            'Air Masses',
            'Fronts',
            'Precipitation',
            'World Climate',
          ]},
          { id: 'oceanography', label: 'Oceanography', topics: [
            'Hydrological Cycle',
            'Ocean Relief Features',
            'Temperature of Ocean Waters',
            'Salinity of Ocean Waters',
            'Movements of Ocean Water',
            'El-Nino, La-Nina & ENSO',
          ]},
          { id: 'worldgeo', label: 'World Geography', topics: [
            'Universe and Its Origin',
            'Stars – Formation and Life Cycle',
            'Galaxies and Solar System',
            'Origin of the Earth and The Moon',
            'Motions of the Earth',
            'Origin and Evolution of the Earth',
          ]},
          { id: 'indiageo', label: 'Indian Geography', topics: [
            'India - Location',
            'Indian Rock System',
            'Movement of the Indian Tectonic Plate',
            'Structure and Physiography',
            'Drainage System of India',
            'Climate of India',
            'Natural Vegetation of India',
            'Soils of India',
          ]},
          { id: 'humangeo', label: 'Human Geography', topics: [
            'Agriculture',
            'Resources',
            'Industries',
            'Energy',
            'Maps (India and World)',
          ]},
        ],
      },
      {
        id: 'society', label: 'Society',
        groups: [
          { id: 'society-topics', label: 'Society', topics: [
            'Salient Features of Indian Society',
            'Diversity of India',
            'Role of Women and Women\'s Organizations',
            'Population and Associated Issues',
            'Poverty and Developmental Issues',
            'Urbanization',
            'Globalization',
            'Social Empowerment',
            'Communalism, Regionalism and Secularism',
          ]},
        ],
      },
    ],
  },
  {
    id: 'gs2', label: 'GS — 2',
    subjects: [
      {
        id: 'polity', label: 'Polity',
        groups: [
          { id: 'polity-basics', label: 'Basics', topics: [
            'Historical Background',
            'Indian Constitution',
            'Union and its Territory (Part I)',
            'Citizenship (Part II)',
            'Fundamental Rights (Part III, Articles 12-35)',
            'DPSP (Part IV, Articles 36-51)',
            'Fundamental Duties (Part IV-A, Article 51A)',
            'Amendment of the Constitution (Part XX, Article 368)',
          ]},
          { id: 'union-exec', label: 'Union Executive (Part V, Articles 52–78)', topics: [
            'President (Articles 52-62)',
            'Vice-President (Articles 63-71)',
            'Prime Minister and Council of Ministers (Articles 74, 75)',
            'Attorney General of India (Article 76)',
            'Comptroller Audit General (CAG) – Articles 148-151',
          ]},
          { id: 'parliament', label: 'Parliament (Part V, Articles 79–122)', topics: [
            'Composition, Delimitation, Membership, Presiding Officers',
            'Powers, Secretariat, Sessions, Proceedings',
            'Functions of Parliament',
            'Legislative Procedures, Bills and Budget',
          ]},
          { id: 'state-exec', label: 'State Executive and Legislature (Part VI)', topics: [
            'Governor (Articles 153–167)',
            'Chief Minister and State Council of Ministers',
            'State Legislature (Part VI, Articles 168 to 212)',
          ]},
          { id: 'system-govt', label: 'System of Government', topics: [
            'Parliamentary and Federal System',
            'Centre-State Relations – Legislative Relations',
            'Centre-State Relations – Administrative Relations',
            'Centre-State Relations – Financial Relations',
            'Emergency (Part XVIII, Article 352-360)',
          ]},
          { id: 'judiciary', label: 'Judiciary', topics: [
            'Supreme Court (Part V, Articles 124 to 147)',
            'High Court (Part VI, Articles 214-231)',
            'Other Courts and ADR Mechanisms',
          ]},
          { id: 'elections', label: 'Elections', topics: [
            'Elections (Part XV, Articles 324 to 329)',
          ]},
          { id: 'local-gov', label: 'Local Governance (Part IX, IX-A)', topics: [
            'Introduction and Evolution',
            'Panchayati Raj (Part IX, Article 243 to 243-O)',
            'Municipalities (Part IX-A, Articles 243P to 243ZG)',
            'Co-operatives (Part IX-B, Articles 243-ZH to 243-ZT)',
          ]},
          { id: 'ut-tribal', label: 'Union Territories & Tribal Areas', topics: [
            'Union Territories (Part XVIII, Articles 239 to 241)',
            'Fifth Schedule',
            'Sixth Schedule',
          ]},
          { id: 'const-bodies', label: 'Constitutional Bodies', topics: [
            'Public Service Commissions (Part XIV, Articles 315–323)',
            'Special Provisions for Certain Classes (Part XVI, Articles 330–342A)',
          ]},
          { id: 'non-const-bodies', label: 'Non-Constitutional Bodies', topics: [
            'Introduction',
            'Human Rights Bodies',
            'Accountability and Vigilance Bodies',
          ]},
          { id: 'official-lang', label: 'Official Language', topics: [
            'Official Language (Part XVII, Articles 343–351)',
          ]},
        ],
      },
      {
        id: 'governance', label: 'Governance',
        groups: [
          { id: 'governance-topics', label: 'Governance', topics: [
            'Pressure Groups and Associations',
            'Role of Civil Services in Democracy',
            'Government Policies & Interventions for Development',
            'Development Processes: NGOs, SHGs, Donors',
            'Governance, Transparency and All',
          ]},
        ],
      },
      {
        id: 'socialjustice', label: 'Social Justice',
        groups: [
          { id: 'sj-topics', label: 'Social Justice', topics: [
            'Welfare Schemes for Vulnerable Sections',
            'Women and Gender',
            'Children',
            'Scheduled Castes and Scheduled Tribes',
            'Persons with Disabilities',
            'Elderly and Minorities',
            'Health',
            'Education',
            'Poverty and Hunger',
            'Human Resources',
          ]},
        ],
      },
    ],
  },
  {
    id: 'gs3', label: 'GS — 3',
    subjects: [
      {
        id: 'economy', label: 'Economy',
        groups: [
          { id: 'economy-core', label: 'Core Economics', topics: [
            'Introduction to Indian Economy',
            'National Income Accounting',
            'Microeconomics',
            'Growth and Development',
            'Economic Planning',
            'LPG Reforms',
            'Inflation',
            'Monetary Policy',
            'Financial Market',
            'Financial Market Regulatory Bodies',
            'Banking Sector',
            'Public Finance',
            'Taxation',
            'Investment Models',
            'External Sector',
          ]},
          { id: 'agriculture', label: 'Agriculture', topics: [
            'Introduction',
            'Agriculture Inputs',
            'Storage, Transportation and Marketing',
            'Food Processing Industry',
            'Allied Sectors',
            'Miscellaneous',
          ]},
          { id: 'industries', label: 'Industries', topics: [
            'Industries and Services Sector',
          ]},
          { id: 'infrastructure', label: 'Infrastructure', topics: [
            'Introduction',
            'Transport Network',
            'Energy Sector',
            'Other Sectors',
          ]},
          { id: 'intl-econ', label: 'International', topics: [
            'International Economic Organisations',
          ]},
        ],
      },
      {
        id: 'scitech', label: 'Science and Technology',
        groups: [
          { id: 'scitech-core', label: 'Science and Technology', topics: [
            'General Science Basics',
            'Space Technology',
            'Energy Science',
            'Nuclear Technology',
            'Defence Technology',
            'Information Technology, Computers and Robotics',
            'Frontier Technologies',
          ]},
          { id: 'biology', label: 'Biology', topics: [
            'Foundations of Life',
            'Human Body Systems',
            'Microorganisms and Diseases',
            'Immunity and Vaccines',
            'Plant Science',
            'Biotechnology',
          ]},
        ],
      },
      {
        id: 'environment', label: 'Environment',
        groups: [
          { id: 'env-topics', label: 'Environment', topics: [
            'Basic Concepts of Ecosystem',
            'Ecosystems',
            'Biodiversity',
            'Pollution and Control',
            'Climate Change',
            'Environment Impact Assessment (EIA)',
            'Indian Institutions',
            'Environment Conventions',
          ]},
        ],
      },
      {
        id: 'disaster', label: 'Disaster Management',
        groups: [
          { id: 'disaster-topics', label: 'Disaster Management', topics: [
            'Disaster Management',
          ]},
        ],
      },
      {
        id: 'security', label: 'Internal Security',
        groups: [
          { id: 'security-topics', label: 'Internal Security', topics: [
            'Development-Extremism Link',
            'External State & Non-State Actors',
            'Communication Networks, Social Media and All',
            'Border Security and Terrorism',
            'Security Forces & Agencies',
          ]},
        ],
      },
    ],
  },
  {
    id: 'gs4', label: 'GS — 4',
    subjects: [
      {
        id: 'ethics', label: 'Ethics',
        groups: [
          { id: 'ethics-topics', label: 'Ethics', topics: [
            'The Vocabulary of Ethics',
            'Ethics and Human Interface',
            'Indian Ethical Traditions',
            'Attitude',
            'Aptitude and Foundational Values for Civil Services',
            'Emotional Intelligence',
            'Moral Thinkers and Philosophers',
            'Public/Civil Service Values and Ethics in Public Administration',
            'Probity in Governance',
            'Contemporary and Applied Ethics',
            'Case Studies',
          ]},
        ],
      },
    ],
  },
  {
    id: 'optionals', label: 'Optionals',
    subjects: [
      {
        id: 'psir1a', label: 'PSIR — 1A',
        groups: [
          { id: 'psir1a-intro', label: 'Introduction', topics: [
            'Political Theory',
          ]},
          { id: 'wpt', label: 'Western Political Thought', topics: [
            'Socrates and Plato',
            'Aristotle',
            'Machiavelli',
            'Hobbes',
            'John Locke',
            'Rousseau',
            'JS Mill',
            'Marx',
            'Gramsci',
            'Hannah Arendt',
          ]},
          { id: 'pol-ideologies', label: 'Political Ideologies', topics: [
            'Ideology & Idealism',
            'Liberalism',
            'Socialism',
            'Marxism',
            'Fascism',
            'Feminism',
            'Post-Modernism',
            'Post-Colonialism',
            'Multi-Culturalism',
            'Value Pluralism',
            'End of Ideology & History',
            'Clash of Civilizations',
          ]},
          { id: 'ipt', label: 'Indian Political Thought', topics: [
            'Introduction',
            'Dharmashastra',
            'Arthashastra',
            'Buddhist',
            'Sir Syed Ahmed Khan',
            'Sir Aurobindo',
            'M.N Roy',
            'Gandhi',
            'Ambedkar',
          ]},
          { id: 'theories', label: 'Theories', topics: [
            'State',
            'Power',
            'Democracy',
            'Rights',
            'Justice',
            'Equality',
          ]},
        ],
      },
      {
        id: 'psir1b', label: 'PSIR — 1B',
        groups: [
          { id: 'psir1b-topics', label: 'PSIR 1B', topics: [
            'Indian Nationalism',
            'Making of Indian Constitution',
            'Salient Features of Indian Constitution',
            'Principal Organs of Government',
            'Grassroot Democracy',
            'Federalism',
            'Planning & Economic Development',
            'Caste, Religion, Ethnicity in Politics',
            'Party System',
            'Social Movements',
          ]},
        ],
      },
      {
        id: 'psir2a', label: 'PSIR — 2A',
        groups: [
          { id: 'psir2a-topics', label: 'PSIR 2A', topics: [
            'Comparative Politics',
            'State in Comparative Politics',
            'Representation & Participation in Politics',
            'Globalisation',
            'Approaches to Study of IR',
            'Key Concepts in IR',
            'Changing International Political Order',
            'Evolution of International Economic System',
            'United Nations',
            'Regionalisation',
            'Contemporary Global Concerns',
          ]},
        ],
      },
      {
        id: 'psir2b', label: 'PSIR — 2B',
        groups: [
          { id: 'psir2b-topics', label: 'PSIR 2B', topics: [
            'Indian Foreign Policy',
            'India\'s Contribution to NAM',
            'India and South Asia',
            'India and Global South',
            'India and Global Centres of Power',
            'India and UN System',
            'India and Nuclear Question',
            'Recent Developments in Policy',
          ]},
        ],
      },
    ],
  },
  {
    id: 'other', label: 'Other',
    subjects: [
      { id: 'csat',    label: 'CSAT',           groups: null },
      { id: 'essays',  label: 'Essays',          groups: null },
      { id: 'ca',      label: 'Current Affairs', groups: null },
    ],
  },
];
